import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs';


export const metadata: Metadata = {
  title: "OSPC X IEEE RAS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>

    <html lang="en" className="bg-slate-200 text-black">
      <body>
        {children}
      </body>
    </html>
    </ClerkProvider>

  );
}
